# SITE CONFIGURATION
title: Sky Shi
author: Sky Shi
description: >
  Welcome! I'm Kaiyuan Shi. I'm interested in the fundamental structures of this universe.
baseurl: "/Sky Shi"
url: "https://kaiyuan-shi.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Sky Shi
  I know there should be some "social media" section here. But I don't use any of them.
  Please see the contact section to find me.

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'Projects', link: '/Projects'}
  - {na,e: 'CV', link: '/CV'}
  - {name: 'Contact', link: '/Contact'}

tagline: >
  Modern Jekyll theme focused on speed performance &amp; SEO best practices

hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: skyshi@g.ucla.edu # email for form submission

disqus:
  shortname: Sky Shi

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
