# SITE CONFIGURATION
title: Sky's Personal Homepage
author: Sky Shi
description: >
  Welcome! I'm Kaiyuan Shi. I'm interested in the fundamental structures of this universe. 
baseurl: ""
url: "https://kaiyuan-shi.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/Projects'}
  - {name: 'Projects', link: '/'}
  - {name: 'About Me', link: '/About Me'}
  - {name: 'Contact', link: '/Contact'}

tagline: >
  Welcome to my homepage!
  Sky is currently seeking research opportunities as a Ph.D. student.
  Sky is interested in the fundamental structures of this universe- the particles that make up our world.
  Sky enjoy his works in both experiment and theory groups during his undergraduate research experiences, and he is interested in both of them.
  
  
hero_img: posts/SB_sunset.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: skyshi@g.ucla.edu # email for form submission

disqus:
  shortname: Sky Shi

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
